# Generated by Django 3.2.2 on 2021-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combate', '0002_alter_proveedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='idAnuncio',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
